version: "3.8"

networks:
    collab:

version: "3.8"

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
        - collab

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        depends_on:
        - zookeeper
        environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        networks:
        - collab
        ports:
        - "9092:9092"

    server:
        image: server
        container_name: server
        networks:
            - collab
        volumes:
            - ./src:/home/CollabEdit/src
        ports:
            - "8080:8080"
        command: ["node", "src/server.js"]

    web:
        image: node:18-alpine
        container_name: web
        networks:
            - collab
        volumes:
            - ./src:/usr/src/
        working_dir: /usr/src
        command: ["npx", "http-server", ".", "-p", "8000", "-c-1", "--cors"]
        ports:
            - "8000:8000"

    web1:
        image: node:18-alpine
        container_name: web1
        networks:
            - collab
        volumes:
            - ./src:/usr/src/
        working_dir: /usr/src
        command: ["npx", "http-server", ".", "-p", "8001", "-c-1", "--cors"]
        ports:
            - "8001:8001"
