version: "3.8"

networks:
    collab:
        driver: bridge

services:
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - collab
        ports:
            - "6379:6379"

    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            - BITNAMI_DEBUG=false
            - ZOO_LOG_LEVEL=ERROR
        networks:
            - collab

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_LOG4J_LOGGERS=kafka.controller=ERROR,kafka.log.LogCleaner=ERROR,kafka.server=ERROR,kafka.coordinator=ERROR
            - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
        volumes:
            - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
        networks:
            - collab
        ports:
            - "9092:9092"

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        networks:
            - collab
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d

    auth:
        build:
            context: ./src/auth
            dockerfile: Dockerfile
        container_name: auth
        networks:
            - collab
        environment:
            - DB_HOST=mariadb
            - DB_USER=${MARIADB_USER}
            - DB_PASSWORD=${MARIADB_PASSWORD}
            - DB_NAME=${MARIADB_DATABASE}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        ports:
            - "3001:3001"
        volumes:
            - ./src/auth:/home/CollabEdit/src

    api-gateway:
        build:
            context: ./src/api-gateway
            dockerfile: Dockerfile
        container_name: api-gateway
        networks:
            - collab
        ports:
            - "3000:3000"
        volumes:
            - ./src/api-gateway:/home/CollabEdit/src

    web:
        image: node:18-alpine
        container_name: web
        networks:
            - collab
        volumes:
            - ./src/client:/usr/src/
        working_dir: /usr/src/
        command:
            [
                "npx",
                "http-server",
                ".",
                "-p",
                "8000",
                "-c-1",
                "--cors",
                "-i",
                "index.html",
            ]
        ports:
            - "8000:8000"

    documents:
        build:
            context: ./src/documents
            dockerfile: Dockerfile
        container_name: documents
        networks:
            - collab
        environment:
            - DB_HOST=mariadb
            - DB_USER=${MARIADB_USER}
            - DB_PASSWORD=${MARIADB_PASSWORD}
            - DB_NAME=${MARIADB_DATABASE}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - "3002:3002"
        volumes:
            - ./src/documents:/home/CollabEdit/src

    collab:
        build:
            context: ./src/collab
            dockerfile: Dockerfile
        container_name: collab
        depends_on:
            - mariadb
            - kafka
            - redis
        networks:
            - collab
        environment:
            - DB_HOST=mariadb
            - DB_USER=${MARIADB_USER}
            - DB_PASSWORD=${MARIADB_PASSWORD}
            - DB_NAME=${MARIADB_DATABASE}
            - JWT_SECRET=${JWT_SECRET}
        ports:
            - "8080:8080"
        volumes:
            - ./src/collab:/home/CollabEdit/src

volumes:
    mariadb_data: