networks:
    collab:

version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        networks:
            - collab
        ports:
            - "6379:6379"

    zookeeper:
        image: bitnami/zookeeper:latest
        container_name: zookeeper
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
            - BITNAMI_DEBUG=false
            - ZOO_LOG_LEVEL=ERROR
        networks:
            - collab

    kafka:
        image: bitnami/kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
            - KAFKA_LOG4J_LOGGERS=kafka.controller=ERROR,kafka.log.LogCleaner=ERROR,kafka.server=ERROR,kafka.coordinator=ERROR
            - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
        volumes:
            - ./log4j.properties:/opt/bitnami/kafka/config/log4j.properties
        networks:
            - collab
        ports:
            - "9092:9092"

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: always
        networks:
            - collab
        environment:
            - MARIADB_ROOT_PASSWORD=rootpassword
            - MARIADB_DATABASE=collabedit
            - MARIADB_USER=collabuser
            - MARIADB_PASSWORD=collabpassword
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql

    server:
        image: server
        container_name: server
        depends_on:
            - mariadb
        networks:
            - collab
        volumes:
            - ./src/server:/home/CollabEdit/src
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=mariadb
            - DB_USER=collabuser
            - DB_PASSWORD=collabpassword
            - DB_NAME=collabedit
        command: ["node", "src/server.js"]

    web:
        image: node:18-alpine
        container_name: web
        networks:
            - collab
        volumes:
            - ./src/client:/usr/src/
        working_dir: /usr/src/
        command: ["npx", "http-server", ".", "-p", "8000", "-c-1", "--cors"]
        ports:
            - "8000:8000"

    web1:
        image: node:18-alpine
        container_name: web1
        networks:
            - collab
        volumes:
            - ./src/client:/usr/src/
        working_dir: /usr/src
        command: ["npx", "http-server", ".", "-p", "8001", "-c-1", "--cors"]
        ports:
            - "8001:8001"

volumes:
    mariadb_data:
